import { forwardRef } from "react";
import { format } from "date-fns";

interface PrintCounterSalesReportProps {
  result: any[];
  singleCms: any;
  userName: string;
  startDate: string;
  endDate: string;
}

const PrintCounterSalesReport = forwardRef<
  HTMLDivElement,
  PrintCounterSalesReportProps
>(
  (
    { 
      result, 
      userName, 
      startDate, 
      endDate 
    },
    ref
  ) => {
    const currentDate = format(new Date(), "M/d/yy, h:mm a");
    
    // Calculate totals for the summary row (same as PDF)
    const totalSoldSeat = result?.reduce((sum: number, s: any) => sum + (s.totalSoldSeat || 0), 0);
    const totalFare = result?.reduce((sum: number, s: any) => sum + (s.totalFare || 0), 0);
    const totalCommissionFee = result?.reduce((sum: number, s: any) => sum + (s.commissionFee || 0), 0);

    return (
      <div
        ref={ref}
        className="flex justify-center items-center p-6 min-h-screen hidden print:block"
      >
        {/* Report container */}
        <div className="flex flex-col rounded-2xl overflow-hidden w-full max-w-[1000px] bg-white border-2 border-gray-300">
          {/* Blue Header */}
          <div className="bg-gradient-to-r from-sky-400 to-sky-600 text-white px-6 py-3 flex justify-between items-center">
            <h2 className="text-xl font-bold">Iconic Express</h2>
            <p className="text-sm">Counter Wise Sales Report</p>
          </div>

          {/* Report Info */}
          <div className="px-6 py-4 bg-gray-100">
            <div className="flex justify-between gap-4 text-sm">
              <div>
                <div><span className="font-semibold">Generated By:</span> {userName}</div>
                <div><span className="font-semibold">Date:</span> {currentDate}</div>
              </div>
              <div>
                <div><span className="font-semibold">Period:</span> {startDate} to {endDate}</div>
                <div><span className="font-semibold">Total Records:</span> {result?.length || 0}</div>
              </div>
            </div>
          </div>

          {/* Report Body */}
          <div className="px-6 py-4">
            {/* Table - Matching the PDF structure */}
            <div className="overflow-x-auto">
              <table className="w-full border-collapse border border-gray-400 text-xs">
                <thead>
                  <tr className="bg-gray-200">
                    <th className="border border-gray-400 p-1">SL</th>
                    <th className="border border-gray-400 p-1">Travel Date</th>
                    <th className="border border-gray-400 p-1">Sold Seat Qty</th>
                    <th className="border border-gray-400 p-1">Fare</th>
                    <th className="border border-gray-400 p-1">Commission Fare</th>
                  </tr>
                </thead>
                <tbody>
                  {result?.map((sale: any, index: number) => (
                    <tr key={sale.id || index} className="hover:bg-gray-50">
                      <td className="border border-gray-400 p-1 text-center">{index + 1}</td>
                      <td className="border border-gray-400 p-1 text-center">{sale?.date || "N/A"}</td>
                      <td className="border border-gray-400 p-1 text-center">{sale?.totalSoldSeat || 0}</td>
                      <td className="border border-gray-400 p-1 text-center">{sale?.totalFare || 0}</td>
                      <td className="border border-gray-400 p-1 text-center">{sale?.commissionFee || 0}</td>
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr className="bg-gray-100 font-bold">
                    <td className="border border-gray-400 p-1 text-right" colSpan={2}>Total:</td>
                    <td className="border border-gray-400 p-1 text-center">{totalSoldSeat}</td>
                    <td className="border border-gray-400 p-1 text-center">{totalFare}</td>
                    <td className="border border-gray-400 p-1 text-center">{totalCommissionFee}</td>
                  </tr>
                </tfoot>
              </table>
            </div>

            {/* Summary Section */}
            <div className="mt-6 p-4 bg-gray-100 rounded-lg">
              <h3 className="font-bold text-lg mb-2">Summary</h3>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div><span className="font-semibold">Total Records:</span> {result?.length || 0}</div>
                <div><span className="font-semibold">Total Sold Seats:</span> {totalSoldSeat}</div>
                <div><span className="font-semibold">Total Fare:</span> {totalFare}</div>
                <div><span className="font-semibold">Total Commission Fee:</span> {totalCommissionFee}</div>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="bg-gray-200 px-6 py-3 text-center text-xs">
            <p>Generated by Iconic Express Sales System</p>
            <p>{currentDate}</p>
          </div>
        </div>
      </div>
    );
  }
);

PrintCounterSalesReport.displayName = "PrintCounterSalesReport";

export default PrintCounterSalesReport;