import { forwardRef } from "react";
import { format } from "date-fns";

interface PrintUserWiseSalesReportProps {
  result: any[];
  singleCms: any;
  userName: string;
  counter: string;
  selectedUser: string;
  startDate: string;
  endDate: string;
}

const PrintCounterWiseSalesReport = forwardRef<
  HTMLDivElement,
  PrintUserWiseSalesReportProps
>(
  (
    { 
      result, 
      userName, 
      startDate, 
      endDate 
    },
    ref
  ) => {
    const currentDate = format(new Date(), "M/d/yy, h:mm a");
    
    // Calculate totals like in the PDF component
    const totalSold = result?.reduce((sum: number, s: any) => sum + (s.totalSold || 0), 0);
    const totalCancel = result?.reduce((sum: number, s: any) => sum + (s.totalCancel || 0), 0);
    const actualSold = result?.reduce((sum: number, s: any) => sum + (s.actualSold || 0), 0);
    const totalFare = result?.reduce((sum: number, s: any) => sum + (s.totalFare || 0), 0);
    const refundAmount = result?.reduce((sum: number, s: any) => sum + (s.refundAmount || 0), 0);
    const totalCommission = result?.reduce((sum: number, s: any) => sum + (s.totalCommission || 0), 0);
    const deposit = result?.reduce((sum: number, s: any) => sum + (s.deposit || 0), 0);

    return (
      <div
        ref={ref}
        className="flex justify-center items-center p-6 min-h-screen hidden print:block"
      >
        {/* Report container */}
        <div className="flex flex-col rounded-2xl overflow-hidden w-full max-w-[1000px] bg-white border-2 border-gray-300">
          {/* Blue Header */}
          <div className="bg-gradient-to-r from-sky-400 to-sky-600 text-white px-6 py-3 flex justify-between items-center">
            <h2 className="text-xl font-bold">Iconic Express</h2>
            <p className="text-sm">All Counter User Wise Sales Report</p>
          </div>

          {/* Report Info */}
          <div className="px-6 py-4 bg-gray-100">
            <div className="flex justify-between gap-4 text-sm">
              <div>
                <div><span className="font-semibold">Generated By:</span> {userName}</div>
                <div><span className="font-semibold">Date:</span> {currentDate}</div>
              </div>
              <div>
                <div><span className="font-semibold">Period:</span> {startDate} to {endDate}</div>
                <div><span className="font-semibold">Total Records:</span> {result?.length || 0}</div>
              </div>
            </div>
          </div>

          {/* Report Body */}
          <div className="px-6 py-4">
            {/* Table */}
            <div className="overflow-x-auto">
              <table className="w-full border-collapse border border-gray-400 text-xs">
                <thead>
                  <tr className="bg-gray-200">
                    <th className="border border-gray-400 p-1">SL</th>
                    <th className="border border-gray-400 p-1">Counter Name</th>
                    <th className="border border-gray-400 p-1">User Name</th>
                    <th className="border border-gray-400 p-1">Total Sold</th>
                    <th className="border border-gray-400 p-1">Total Cancel</th>
                    <th className="border border-gray-400 p-1">Actual Sold</th>
                    <th className="border border-gray-400 p-1">Total Fare</th>
                    <th className="border border-gray-400 p-1">Total Refund</th>
                    <th className="border border-gray-400 p-1">Total Commission</th>
                    <th className="border border-gray-400 p-1">Deposit</th>
                  </tr>
                </thead>
                <tbody>
                  {result?.map((sale: any, index: number) => (
                    <tr key={sale.id} className="hover:bg-gray-50">
                      <td className="border border-gray-400 p-1 text-center">{index + 1}</td>
                      <td className="border border-gray-400 p-1 text-center">{sale?.counter || "N/A"}</td>
                      <td className="border border-gray-400 p-1 text-center">{sale?.userName || "N/A"}</td>
                      <td className="border border-gray-400 p-1 text-center">{sale?.totalSold || 0}</td>
                      <td className="border border-gray-400 p-1 text-center">{sale?.totalCancel || 0}</td>
                      <td className="border border-gray-400 p-1 text-center">{sale?.actualSold || 0}</td>
                      <td className="border border-gray-400 p-1 text-center">{sale?.totalFare || 0}</td>
                      <td className="border border-gray-400 p-1 text-center">{sale?.refundAmount || 0}</td>
                      <td className="border border-gray-400 p-1 text-center">{sale?.totalCommission || 0}</td>
                      <td className="border border-gray-400 p-1 text-center">{sale?.deposit || 0}</td>
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr className="bg-gray-100 font-bold">
                    <td className="border border-gray-400 p-1 text-right" colSpan={3}>Total:</td>
                    <td className="border border-gray-400 p-1 text-center">{totalSold}</td>
                    <td className="border border-gray-400 p-1 text-center">{totalCancel}</td>
                    <td className="border border-gray-400 p-1 text-center">{actualSold}</td>
                    <td className="border border-gray-400 p-1 text-center">{totalFare}</td>
                    <td className="border border-gray-400 p-1 text-center">{refundAmount}</td>
                    <td className="border border-gray-400 p-1 text-center">{totalCommission}</td>
                    <td className="border border-gray-400 p-1 text-center">{deposit}</td>
                  </tr>
                </tfoot>
              </table>
            </div>

            {/* Summary Section */}
            <div className="mt-6 p-4 bg-gray-100 rounded-lg">
              <h3 className="font-bold text-lg mb-2">Summary</h3>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div><span className="font-semibold">Total Sales Records:</span> {result?.length || 0}</div>
                <div><span className="font-semibold">Total Sold:</span> {totalSold}</div>
                <div><span className="font-semibold">Total Cancel:</span> {totalCancel}</div>
                <div><span className="font-semibold">Actual Sold:</span> {actualSold}</div>
                <div><span className="font-semibold">Total Fare:</span> {totalFare}</div>
                <div><span className="font-semibold">Total Refund:</span> {refundAmount}</div>
                <div><span className="font-semibold">Total Commission:</span> {totalCommission}</div>
                <div><span className="font-semibold">Total Deposit:</span> {deposit}</div>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="bg-gray-200 px-6 py-3 text-center text-xs">
            <p>Generated by Iconic Express Sales System</p>
            <p>{currentDate}</p>
          </div>
        </div>
      </div>
    );
  }
);

PrintCounterWiseSalesReport.displayName = "PrintCounterWiseSalesReport";

export default PrintCounterWiseSalesReport;