import { forwardRef } from "react";
import { format } from "date-fns";

interface PrintUserWiseSalesReportProps {
  result: any[];
  singleCms: any;
  userName: string;
  counter: string;
  selectedUser: string;
  startDate: string;
  endDate: string;
}

const PrintUserWiseSalesReport = forwardRef<
  HTMLDivElement,
  PrintUserWiseSalesReportProps
>(
  (
    { 
      result, 
      // singleCms, 
      userName, 
      counter, 
      selectedUser, 
      startDate, 
      endDate 
    },
    ref
  ) => {
    const currentDate = format(new Date(), "M/d/yy, h:mm a");
    const totalFare = result?.reduce(
      (sum: number, s: any) => sum + (s.unitPrice || 0),
      0
    );
    const totalDiscount = result?.reduce(
      (sum: number, s: any) => sum + (s.discount || 0),
      0
    );

    return (
      <div
        ref={ref}
        className="flex justify-center items-center p-6 min-h-screen hidden print:block"
      >
        {/* Report container */}
        <div className="flex flex-col rounded-2xl overflow-hidden w-[950px] bg-white border-2 border-gray-300">
          {/* Blue Header */}
          <div className="bg-gradient-to-r from-sky-400 to-sky-600 text-white px-6 py-3 flex justify-between items-center">
            <h2 className="text-xl font-bold">Iconic Express</h2>
            <p className="text-sm">User Wise Sales Report</p>
          </div>

          {/* Report Info */}
          <div className="px-6 py-4 bg-gray-100">
            <div className="flex justify-between gap-4 text-sm">
              <div>
                <div>
                <span className="font-semibold">Generated By:</span> {userName}
              </div>
              <div>
                <span className="font-semibold">Date:</span> {currentDate}
              </div>
              <div>
                <span className="font-semibold">Counter:</span> {counter}
              </div>
              </div>
             <div>
               <div>
                <span className="font-semibold">User:</span> {selectedUser}
              </div>
              <div>
                <span className="font-semibold">Period:</span> {startDate} to {endDate}
              </div>
              <div>
                <span className="font-semibold">Total Records:</span> {result?.length || 0}
              </div>
             </div>
            </div>
          </div>

          {/* Report Body */}
          <div className="px-6 py-4">
            {/* Table */}
            <div className="overflow-x-auto">
              <table className="w-full border-collapse border border-gray-400 text-xs">
                <thead>
                  <tr className="bg-gray-200">
                    <th className="border border-gray-400 p-2">SL</th>
                    <th className="border border-gray-400 p-2">Travel Date</th>
                    <th className="border border-gray-400 p-2">Coach No</th>
                    <th className="border border-gray-400 p-2">Class</th>
                    <th className="border border-gray-400 p-2">Seat</th>
                    <th className="border border-gray-400 p-2">Status</th>
                    <th className="border border-gray-400 p-2">Cancel By</th>
                    <th className="border border-gray-400 p-2">Fare</th>
                    <th className="border border-gray-400 p-2">Discount</th>
                    <th className="border border-gray-400 p-2">Actual Fare</th>
                  </tr>
                </thead>
                <tbody>
                  {result?.map((sale: any, index: number) => (
                    <tr key={sale.id} className="hover:bg-gray-50">
                      <td className="border border-gray-400 p-2 text-center">
                        {index + 1}
                      </td>
                      <td className="border border-gray-400 p-2 text-center">
                        {sale?.coachConfig?.departureDate || "N/A"}
                      </td>
                      <td className="border border-gray-400 p-2 text-center">
                        {sale?.coachConfig?.coachNo || "N/A"}
                      </td>
                      <td className="border border-gray-400 p-2 text-center">
                        {sale?.class || "N/A"}
                      </td>
                      <td className="border border-gray-400 p-2 text-center">
                        {sale?.seat || "N/A"}
                      </td>
                      <td className="border border-gray-400 p-2 text-center">
                        {sale?.status || "N/A"}
                      </td>
                      <td className="border border-gray-400 p-2 text-center">
                        {sale?.cancelBy ? sale?.cancelBy : "N/A"}
                      </td>
                      <td className="border border-gray-400 p-2 text-center">
                        {sale?.unitPrice || 0}
                      </td>
                      <td className="border border-gray-400 p-2 text-center">
                        {sale?.discount || 0}
                      </td>
                      <td className="border border-gray-400 p-2 text-center">
                        {(sale?.unitPrice || 0) - (sale?.discount || 0)}
                      </td>
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr className="bg-gray-100 font-bold">
                    <td
                      className="border border-gray-400 p-2 text-right"
                      colSpan={7}
                    >
                      Total:
                    </td>
                    <td className="border border-gray-400 p-2 text-center">
                      {totalFare}
                    </td>
                    <td className="border border-gray-400 p-2 text-center">
                      {totalDiscount}
                    </td>
                    <td className="border border-gray-400 p-2 text-center">
                      {totalFare - totalDiscount}
                    </td>
                  </tr>
                </tfoot>
              </table>
            </div>

            {/* Summary Section */}
            <div className="mt-6 p-4 bg-gray-100 rounded-lg">
              <h3 className="font-bold text-lg mb-2">Summary</h3>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <span className="font-semibold">Total Sales:</span> {result?.length || 0}
                </div>
                <div>
                  <span className="font-semibold">Total Fare:</span> {totalFare}
                </div>
                <div>
                  <span className="font-semibold">Total Discount:</span> {totalDiscount}
                </div>
                <div>
                  <span className="font-semibold">Net Amount:</span> {totalFare - totalDiscount}
                </div>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="bg-gray-200 px-6 py-3 text-center text-xs">
            <p>Generated by Iconic Express Sales System</p>
            <p>{currentDate}</p>
          </div>
        </div>
      </div>
    );
  }
);

PrintUserWiseSalesReport.displayName = "PrintUserWiseSalesReport";

export default PrintUserWiseSalesReport;