export interface INationalityOptionsProps {
  en: string;
  bn: string;
  key: string;
}
export const nationalitiesOptions: INationalityOptionsProps[] = [
  { key: "afghan", en: "Afghan", bn: "আফগান" },
  { key: "american", en: "American", bn: "আমেরিকান" },
  { key: "australian", en: "Australian", bn: "অস্ট্রেলিয়ান" },
  { key: "bangladeshi", en: "Bangladeshi", bn: "বাংলাদেশি" },
  { key: "brazilian", en: "Brazilian", bn: "ব্রাজিলিয়ান" },
  { key: "british", en: "British", bn: "ব্রিটিশ" },
  { key: "canadian", en: "Canadian", bn: "কানাডিয়ান" },
  { key: "chinese", en: "Chinese", bn: "চীনা" },
  { key: "egyptian", en: "Egyptian", bn: "মিশরীয়" },
  { key: "french", en: "French", bn: "ফরাসি" },
  { key: "german", en: "German", bn: "জার্মান" },
  { key: "indian", en: "Indian", bn: "ভারতীয়" },
  { key: "indonesian", en: "Indonesian", bn: "ইন্দোনেশিয়ান" },
  { key: "iranian", en: "Iranian", bn: "ইরানী" },
  { key: "iraqi", en: "Iraqi", bn: "ইরাকি" },
  { key: "irish", en: "Irish", bn: "আইরিশ" },
  { key: "italian", en: "Italian", bn: "ইতালীয়" },
  { key: "japanese", en: "Japanese", bn: "জাপানিজ" },
  { key: "korean", en: "Korean", bn: "কোরিয়ান" },
  { key: "malaysian", en: "Malaysian", bn: "মালয়েশিয়ান" },
  { key: "mexican", en: "Mexican", bn: "মেক্সিকান" },
  { key: "nepalese", en: "Nepalese", bn: "নেপালি" },
  { key: "nigerian", en: "Nigerian", bn: "নাইজেরিয়ান" },
  { key: "pakistani", en: "Pakistani", bn: "পাকিস্তানি" },
  { key: "philippine", en: "Philippine", bn: "ফিলিপিনো" },
  { key: "russian", en: "Russian", bn: "রাশিয়ান" },
  { key: "saudi_arabian", en: "Saudi Arabian", bn: "সৌদি" },
  { key: "singaporean", en: "Singaporean", bn: "সিঙ্গাপুরিয়ান" },
  { key: "south_african", en: "South African", bn: "দক্ষিণ আফ্রিকান" },
  { key: "spanish", en: "Spanish", bn: "স্প্যানিশ" },
  { key: "sri_lankan", en: "Sri Lankan", bn: "শ্রীলঙ্কান" },
  { key: "sudanese", en: "Sudanese", bn: "সুদানী" },
  { key: "swedish", en: "Swedish", bn: "সুইডিশ" },
  { key: "swiss", en: "Swiss", bn: "সুইস" },
  { key: "syrian", en: "Syrian", bn: "সিরিয়ান" },
  { key: "thai", en: "Thai", bn: "থাই" },
  { key: "turkish", en: "Turkish", bn: "তুর্কি" },
  { key: "ukrainian", en: "Ukrainian", bn: "ইউক্রেনীয়" },
  { key: "emirati", en: "Emirati", bn: "আমিরাতি" },
  { key: "vietnamese", en: "Vietnamese", bn: "ভিয়েতনামী" },
];
