import { Router } from "express";
import authRouter from "../module/auth/auth.index";
import userRouter from "../module/user/user.index";
import coachRouter from "../module/coach/coach.index";
import driverRouter from "../module/driver/driver.index";
import counterRouter from "../module/counter/counter.index";
import stationRouter from "../module/station/station.index";
import routeRouter from "../module/route/route.index";
import scheduleRouter from "../module/schedule/schedule.index";
import coachConfigRouter from "../module/coachConfig/coachConfig.index";
import fareRouter from "../module/fare/fare.index";
import customerRouter from "../module/customer/customer.index";
import seatRouter from "../module/seat/seat.index";
import accountRouter from "../module/account/account.index";
import orderRouter from "../module/order/order.index";
import expenseRouter from "../module/expense/expense.index";
import expenseCategoryRouter from "../module/expenseCategory/expenseCategory.index";
import collectionRouter from "../module/collection/collection.index";
import discountRouter from "../module/discount/discount.index";
import paymentRouter from "../module/payment/payment.index";
import investorRouter from "../module/investor/investor.index";
import investingRouter from "../module/investing/investing.index";
import cmsRouter from "../module/cms/cms.index";
import expenseSubCategoryRouter from "../module/expenseSubCategory/expenseSubCategory.index";
import vehicleRouter from "../module/vehicle/vehicle.index";
import balanceTransferRouter from "../module/balanceTransfer/balanceTransfer.index";
import uploadRouter from "../module/fileUpload";
import permissionTypeRouter from "../module/permissionType/permissionType.index";
import permissionRouter from "../module/permission/permission.index";
import rolePermissionRouter from "../module/rolePermission/rolePermission.index";
import roleRouter from "../module/role/role.index";
import reserveRouter from "../module/reserve/reserve.index";
import adminRouter from "../module/admin/admin.index";
import fuelCompanyRouter from "../module/fuelCompany/fuelCompany.index";
import helperRouter from "../module/helper/helper.index";
import sliderRouter from "../module/slider/slider.index";
import expenseAccountsRouter from "../module/expenseAccounts/expenseAccounts.index";
import expenseCategoryAccountsRouter from "../module/expenseCategoryAccounts/expenseCategoryAccounts.index";
import expenseSubCategoryAccountsRouter from "../module/expenseSubCategoryAccounts/expenseSubCategoryAccounts.index";
import partialRouter from "../module/partialInfo/partitalInfo.index";
import aboutUsRouter from "../module/about-us/aboutUs.index";
import busRouter from "../module/bus/bus.index";
import fundPrepaidRouter from "../module/fundPrepaid/fundPrepaid.index";
import coachAssignRouter from "../module/coachAssign/coachAssign.index";
import seatPlanRouter from "../module/seatPlan/seatPlan.index";
import sisterConcernRouter from "../module/sisterConcern/sisterConcern.index";
import coreValueRouter from "../module/coreValue/coreValue.index";
import pagesRouter from "../module/pages/pages.index";
import blogCategoryRouter from "../module/blogCategory/blogCategory.index";
import blogRouter from "../module/blog/blog.index";
import offeredRouter from "../module/offered/offered.index";
import faqRouter from "../module/faq/faq.index";
import userStaticsRouter from "../module/userStatics/userStatics.index";
import reviewRouter from "../module/rating/rating.index";

const router = Router();

router.use('/auth', authRouter);
router.use('/file', uploadRouter);
router.use('/user', userRouter);
router.use('/coach', coachRouter);
router.use('/driver', driverRouter);
router.use('/helper', helperRouter);
router.use('/counter', counterRouter);
router.use('/station', stationRouter);
router.use('/route', routeRouter);
router.use('/schedule', scheduleRouter);
router.use('/coach-config', coachConfigRouter);
router.use('/fare', fareRouter);
router.use('/customer', customerRouter);
router.use('/seat', seatRouter);
router.use('/account', accountRouter);
router.use('/order', orderRouter);
router.use('/expense', expenseRouter);
router.use('/expense-category', expenseCategoryRouter);
router.use('/expense-accounts', expenseAccountsRouter);
router.use('/expense-category-accounts', expenseCategoryAccountsRouter);
router.use('/expense-subcategory-accounts', expenseSubCategoryAccountsRouter);
router.use('/collection', collectionRouter);
router.use('/discount', discountRouter);
router.use('/payment', paymentRouter);
router.use('/investor', investorRouter);
router.use('/investing', investingRouter);
router.use('/cms', cmsRouter);
router.use('/expense-subcategory', expenseSubCategoryRouter);
router.use('/vehicle', vehicleRouter);
router.use('/balance-transfer', balanceTransferRouter);
router.use('/permission-type', permissionTypeRouter);
router.use('/permission', permissionRouter);
router.use('/role-permission', rolePermissionRouter);
router.use('/role', roleRouter);
router.use('/reserve', reserveRouter);
router.use('/admin', adminRouter);
router.use('/slider', sliderRouter);
router.use('/fuel-company', fuelCompanyRouter);
router.use('/partial', partialRouter);
router.use('/bus', busRouter);
router.use('/about-us', aboutUsRouter);
router.use('/fund-prepaid', fundPrepaidRouter);
router.use('/coach-assign', coachAssignRouter);
router.use('/sister-concern', sisterConcernRouter);
router.use('/core-value', coreValueRouter);
router.use('/pages', pagesRouter);
router.use('/blog-category', blogCategoryRouter);
router.use('/blog', blogRouter);
router.use('/offered', offeredRouter);
router.use('/faq', faqRouter);
router.use('/user-statics', userStaticsRouter);
router.use('/seat-plan', seatPlanRouter);
router.use('/review', reviewRouter);


export default router;




